// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branch.sql

package sqlite

import (
	"context"
	"database/sql"
)

const branchCreate = `-- name: BranchCreate :exec
INSERT INTO branches (id, project_id, name, commit_id) VALUES (?, ?, ?, ?)
`

type BranchCreateParams struct {
	ID        int64         `json:"id"`
	ProjectID int64         `json:"project_id"`
	Name      string        `json:"name"`
	CommitID  sql.NullInt64 `json:"commit_id"`
}

func (q *Queries) BranchCreate(ctx context.Context, arg BranchCreateParams) error {
	_, err := q.db.ExecContext(ctx, branchCreate,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.CommitID,
	)
	return err
}

const branchList = `-- name: BranchList :many
SELECT id, project_id, name, protected, commit_id, updated_at, created_at
FROM branches
WHERE project_id = ?1
  AND (updated_at < ?2 is null or updated_at < ?2 OR (updated_at = ?2 AND id < ?3))
ORDER BY updated_at DESC, id DESC
LIMIT ?4
`

type BranchListParams struct {
	ProjectID     int64        `json:"project_id"`
	LastUpdatedAt sql.NullTime `json:"last_updated_at"`
	LastID        int64        `json:"last_id"`
	Limit         int64        `json:"limit"`
}

func (q *Queries) BranchList(ctx context.Context, arg BranchListParams) ([]Branch, error) {
	rows, err := q.db.QueryContext(ctx, branchList,
		arg.ProjectID,
		arg.LastUpdatedAt,
		arg.LastID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Protected,
			&i.CommitID,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const branchUpdate = `-- name: BranchUpdate :exec
UPDATE branches SET name = ?, commit_id = ?, protected = ? WHERE id = ?
`

type BranchUpdateParams struct {
	Name      string        `json:"name"`
	CommitID  sql.NullInt64 `json:"commit_id"`
	Protected bool          `json:"protected"`
	ID        int64         `json:"id"`
}

func (q *Queries) BranchUpdate(ctx context.Context, arg BranchUpdateParams) error {
	_, err := q.db.ExecContext(ctx, branchUpdate,
		arg.Name,
		arg.CommitID,
		arg.Protected,
		arg.ID,
	)
	return err
}
