// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"context"
)

type Querier interface {
	BranchCreate(ctx context.Context, arg BranchCreateParams) error
	BranchGet(ctx context.Context, arg BranchGetParams) (Branch, error)
	BranchList(ctx context.Context, arg BranchListParams) ([]Branch, error)
	BranchUpdate(ctx context.Context, arg BranchUpdateParams) error
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	DeleteOrganization(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	GetOrganization(ctx context.Context, id int64) (Organization, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetProjectByOrgIDAndID(ctx context.Context, arg GetProjectByOrgIDAndIDParams) (Project, error)
	ListOrganizations(ctx context.Context) ([]Organization, error)
	ListProjectsByOrgId(ctx context.Context, orgID int64) ([]Project, error)
	RefreshTokenCreate(ctx context.Context, arg RefreshTokenCreateParams) (int64, error)
	RefreshTokenDeleteByToken(ctx context.Context, token string) (RefreshToken, error)
	UserCreate(ctx context.Context, arg UserCreateParams) (int64, error)
	UserDeleteByID(ctx context.Context, id int64) error
	UserGetByEmail(ctx context.Context, email string) (User, error)
	UserGetById(ctx context.Context, id int64) (User, error)
	UserUpdatePassword(ctx context.Context, arg UserUpdatePasswordParams) error
	UserUpdateProfile(ctx context.Context, arg UserUpdateProfileParams) error
}

var _ Querier = (*Queries)(nil)
