// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: namespace.sql

package sqlcpg

import (
	"context"
)

const createNamespace = `-- name: CreateNamespace :one
INSERT INTO namespaces (name) VALUES ($1) RETURNING id, name, created_at, updated_at, deleted_at
`

func (q *Queries) CreateNamespace(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, createNamespace, name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteNamespace = `-- name: DeleteNamespace :exec
UPDATE namespaces SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteNamespace(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNamespace, id)
	return err
}

const getNamespace = `-- name: GetNamespace :one
SELECT id, name, created_at, updated_at, deleted_at FROM namespaces WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetNamespace(ctx context.Context, id int64) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, getNamespace, id)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listNamespaces = `-- name: ListNamespaces :many
SELECT id, name, created_at, updated_at, deleted_at FROM namespaces WHERE deleted_at IS NULL ORDER BY id
`

func (q *Queries) ListNamespaces(ctx context.Context) ([]Namespace, error) {
	rows, err := q.db.QueryContext(ctx, listNamespaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Namespace
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
