// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcpg

import (
	"context"
)

type Querier interface {
	CreateNamespace(ctx context.Context, name string) (Namespace, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	DeleteNamespace(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	GetNamespace(ctx context.Context, id int64) (Namespace, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	ListNamespaces(ctx context.Context) ([]Namespace, error)
	ListProjects(ctx context.Context) ([]Project, error)
}

var _ Querier = (*Queries)(nil)
