// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: internal/grpc/proto/server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileMode int32

const (
	FileMode_FILE_MODE_UNSPECIFIED FileMode = 0
	FileMode_FILE_MODE_READ_ONLY   FileMode = 1
	FileMode_FILE_MODE_READ_WRITE  FileMode = 2
	FileMode_FILE_MODE_EXECUTABLE  FileMode = 3
)

// Enum value maps for FileMode.
var (
	FileMode_name = map[int32]string{
		0: "FILE_MODE_UNSPECIFIED",
		1: "FILE_MODE_READ_ONLY",
		2: "FILE_MODE_READ_WRITE",
		3: "FILE_MODE_EXECUTABLE",
	}
	FileMode_value = map[string]int32{
		"FILE_MODE_UNSPECIFIED": 0,
		"FILE_MODE_READ_ONLY":   1,
		"FILE_MODE_READ_WRITE":  2,
		"FILE_MODE_EXECUTABLE":  3,
	}
)

func (x FileMode) Enum() *FileMode {
	p := new(FileMode)
	*p = x
	return p
}

func (x FileMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileMode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_proto_server_proto_enumTypes[0].Descriptor()
}

func (FileMode) Type() protoreflect.EnumType {
	return &file_internal_grpc_proto_server_proto_enumTypes[0]
}

func (x FileMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileMode.Descriptor instead.
func (FileMode) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{0}
}

type ProjectContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectContext) Reset() {
	*x = ProjectContext{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectContext) ProtoMessage() {}

func (x *ProjectContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectContext.ProtoReflect.Descriptor instead.
func (*ProjectContext) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectContext) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ProjectContext) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type FileNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          FileMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=greet.FileMode" json:"mode,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	IsBinary      bool                   `protobuf:"varint,4,opt,name=is_binary,json=isBinary,proto3" json:"is_binary,omitempty"`
	ChunkHashes   []string               `protobuf:"bytes,5,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileNode) Reset() {
	*x = FileNode{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileNode) ProtoMessage() {}

func (x *FileNode) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileNode.ProtoReflect.Descriptor instead.
func (*FileNode) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{1}
}

func (x *FileNode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileNode) GetMode() FileMode {
	if x != nil {
		return x.Mode
	}
	return FileMode_FILE_MODE_UNSPECIFIED
}

func (x *FileNode) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileNode) GetIsBinary() bool {
	if x != nil {
		return x.IsBinary
	}
	return false
}

func (x *FileNode) GetChunkHashes() []string {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type TreeManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeHash      string                 `protobuf:"bytes,1,opt,name=tree_hash,json=treeHash,proto3" json:"tree_hash,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                         // Subdirectory path, e.g., "assets/shaders"
	SubTrees      []*TreeManifest        `protobuf:"bytes,3,rep,name=sub_trees,json=subTrees,proto3" json:"sub_trees,omitempty"` // Child directory trees
	Files         []*FileNode            `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeManifest) Reset() {
	*x = TreeManifest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeManifest) ProtoMessage() {}

func (x *TreeManifest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeManifest.ProtoReflect.Descriptor instead.
func (*TreeManifest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{2}
}

func (x *TreeManifest) GetTreeHash() string {
	if x != nil {
		return x.TreeHash
	}
	return ""
}

func (x *TreeManifest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TreeManifest) GetSubTrees() []*TreeManifest {
	if x != nil {
		return x.SubTrees
	}
	return nil
}

func (x *TreeManifest) GetFiles() []*FileNode {
	if x != nil {
		return x.Files
	}
	return nil
}

type GetTreeManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	TreeHash      *string                `protobuf:"bytes,3,opt,name=tree_hash,json=treeHash,proto3,oneof" json:"tree_hash,omitempty"`
	Recursive     bool                   `protobuf:"varint,4,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeManifestRequest) Reset() {
	*x = GetTreeManifestRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeManifestRequest) ProtoMessage() {}

func (x *GetTreeManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeManifestRequest.ProtoReflect.Descriptor instead.
func (*GetTreeManifestRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{3}
}

func (x *GetTreeManifestRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetTreeManifestRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetTreeManifestRequest) GetTreeHash() string {
	if x != nil && x.TreeHash != nil {
		return *x.TreeHash
	}
	return ""
}

func (x *GetTreeManifestRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type GetTreeManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootTree      *TreeManifest          `protobuf:"bytes,1,opt,name=root_tree,json=rootTree,proto3" json:"root_tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeManifestResponse) Reset() {
	*x = GetTreeManifestResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeManifestResponse) ProtoMessage() {}

func (x *GetTreeManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeManifestResponse.ProtoReflect.Descriptor instead.
func (*GetTreeManifestResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{4}
}

func (x *GetTreeManifestResponse) GetRootTree() *TreeManifest {
	if x != nil {
		return x.RootTree
	}
	return nil
}

type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CommitId      string                 `protobuf:"bytes,3,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{5}
}

func (x *Branch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *Branch) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Branch) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetListBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListBranchRequest) Reset() {
	*x = GetListBranchRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListBranchRequest) ProtoMessage() {}

func (x *GetListBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListBranchRequest.ProtoReflect.Descriptor instead.
func (*GetListBranchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{6}
}

func (x *GetListBranchRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetListBranchRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListBranchRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetListBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextCursor    string                 `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Branches      []*Branch              `protobuf:"bytes,2,rep,name=branches,proto3" json:"branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListBranchResponse) Reset() {
	*x = GetListBranchResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListBranchResponse) ProtoMessage() {}

func (x *GetListBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListBranchResponse.ProtoReflect.Descriptor instead.
func (*GetListBranchResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{7}
}

func (x *GetListBranchResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetListBranchResponse) GetBranches() []*Branch {
	if x != nil {
		return x.Branches
	}
	return nil
}

var File_internal_grpc_proto_server_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_server_proto_rawDesc = "" +
	"\n" +
	" internal/grpc/proto/server.proto\x12\x05greet\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\x0eProjectContext\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\"\xa2\x01\n" +
	"\bFileNode\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x0f.greet.FileModeR\x04mode\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tis_binary\x18\x04 \x01(\bR\bisBinary\x12!\n" +
	"\fchunk_hashes\x18\x05 \x03(\tR\vchunkHashes\"\x98\x01\n" +
	"\fTreeManifest\x12\x1b\n" +
	"\ttree_hash\x18\x01 \x01(\tR\btreeHash\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x120\n" +
	"\tsub_trees\x18\x03 \x03(\v2\x13.greet.TreeManifestR\bsubTrees\x12%\n" +
	"\x05files\x18\x04 \x03(\v2\x0f.greet.FileNodeR\x05files\"\xab\x01\n" +
	"\x16GetTreeManifestRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12 \n" +
	"\ttree_hash\x18\x03 \x01(\tH\x00R\btreeHash\x88\x01\x01\x12\x1c\n" +
	"\trecursive\x18\x04 \x01(\bR\trecursiveB\f\n" +
	"\n" +
	"_tree_hash\"K\n" +
	"\x17GetTreeManifestResponse\x120\n" +
	"\troot_tree\x18\x01 \x01(\v2\x13.greet.TreeManifestR\brootTree\"\xbf\x01\n" +
	"\x06Branch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tcommit_id\x18\x03 \x01(\tR\bcommitId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"u\n" +
	"\x14GetListBranchRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"c\n" +
	"\x15GetListBranchResponse\x12\x1f\n" +
	"\vnext_cursor\x18\x01 \x01(\tR\n" +
	"nextCursor\x12)\n" +
	"\bbranches\x18\x02 \x03(\v2\r.greet.BranchR\bbranches*r\n" +
	"\bFileMode\x12\x19\n" +
	"\x15FILE_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FILE_MODE_READ_ONLY\x10\x01\x12\x18\n" +
	"\x14FILE_MODE_READ_WRITE\x10\x02\x12\x18\n" +
	"\x14FILE_MODE_EXECUTABLE\x10\x032\xab\x01\n" +
	"\vNipaService\x12J\n" +
	"\rGetListBranch\x12\x1b.greet.GetListBranchRequest\x1a\x1c.greet.GetListBranchResponse\x12P\n" +
	"\x0fGetTreeManifest\x12\x1d.greet.GetTreeManifestRequest\x1a\x1e.greet.GetTreeManifestResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_internal_grpc_proto_server_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_server_proto_rawDescData []byte
)

func file_internal_grpc_proto_server_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_server_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_server_proto_rawDesc), len(file_internal_grpc_proto_server_proto_rawDesc)))
	})
	return file_internal_grpc_proto_server_proto_rawDescData
}

var file_internal_grpc_proto_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_grpc_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_grpc_proto_server_proto_goTypes = []any{
	(FileMode)(0),                   // 0: greet.FileMode
	(*ProjectContext)(nil),          // 1: greet.ProjectContext
	(*FileNode)(nil),                // 2: greet.FileNode
	(*TreeManifest)(nil),            // 3: greet.TreeManifest
	(*GetTreeManifestRequest)(nil),  // 4: greet.GetTreeManifestRequest
	(*GetTreeManifestResponse)(nil), // 5: greet.GetTreeManifestResponse
	(*Branch)(nil),                  // 6: greet.Branch
	(*GetListBranchRequest)(nil),    // 7: greet.GetListBranchRequest
	(*GetListBranchResponse)(nil),   // 8: greet.GetListBranchResponse
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_internal_grpc_proto_server_proto_depIdxs = []int32{
	0,  // 0: greet.FileNode.mode:type_name -> greet.FileMode
	3,  // 1: greet.TreeManifest.sub_trees:type_name -> greet.TreeManifest
	2,  // 2: greet.TreeManifest.files:type_name -> greet.FileNode
	1,  // 3: greet.GetTreeManifestRequest.context:type_name -> greet.ProjectContext
	3,  // 4: greet.GetTreeManifestResponse.root_tree:type_name -> greet.TreeManifest
	9,  // 5: greet.Branch.created_at:type_name -> google.protobuf.Timestamp
	9,  // 6: greet.Branch.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 7: greet.GetListBranchRequest.context:type_name -> greet.ProjectContext
	6,  // 8: greet.GetListBranchResponse.branches:type_name -> greet.Branch
	7,  // 9: greet.NipaService.GetListBranch:input_type -> greet.GetListBranchRequest
	4,  // 10: greet.NipaService.GetTreeManifest:input_type -> greet.GetTreeManifestRequest
	8,  // 11: greet.NipaService.GetListBranch:output_type -> greet.GetListBranchResponse
	5,  // 12: greet.NipaService.GetTreeManifest:output_type -> greet.GetTreeManifestResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_server_proto_init() }
func file_internal_grpc_proto_server_proto_init() {
	if File_internal_grpc_proto_server_proto != nil {
		return
	}
	file_internal_grpc_proto_server_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_server_proto_rawDesc), len(file_internal_grpc_proto_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_server_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_server_proto_depIdxs,
		EnumInfos:         file_internal_grpc_proto_server_proto_enumTypes,
		MessageInfos:      file_internal_grpc_proto_server_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_server_proto = out.File
	file_internal_grpc_proto_server_proto_goTypes = nil
	file_internal_grpc_proto_server_proto_depIdxs = nil
}
