// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/branch.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/branch.go -destination=internal/grpc/server/branch_usecase_mock_test.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/nipalab/nipa/internal/domain"
	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MockpermissionUsecase is a mock of permissionUsecase interface.
type MockpermissionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockpermissionUsecaseMockRecorder
	isgomock struct{}
}

// MockpermissionUsecaseMockRecorder is the mock recorder for MockpermissionUsecase.
type MockpermissionUsecaseMockRecorder struct {
	mock *MockpermissionUsecase
}

// NewMockpermissionUsecase creates a new mock instance.
func NewMockpermissionUsecase(ctrl *gomock.Controller) *MockpermissionUsecase {
	mock := &MockpermissionUsecase{ctrl: ctrl}
	mock.recorder = &MockpermissionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpermissionUsecase) EXPECT() *MockpermissionUsecaseMockRecorder {
	return m.recorder
}

// HasProjectAccess mocks base method.
func (m *MockpermissionUsecase) HasProjectAccess(ctx context.Context, projectID snow.ID, permission domain.Permission) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasProjectAccess", ctx, projectID, permission)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasProjectAccess indicates an expected call of HasProjectAccess.
func (mr *MockpermissionUsecaseMockRecorder) HasProjectAccess(ctx, projectID, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasProjectAccess", reflect.TypeOf((*MockpermissionUsecase)(nil).HasProjectAccess), ctx, projectID, permission)
}

// MockbranchRepository is a mock of branchRepository interface.
type MockbranchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockbranchRepositoryMockRecorder
	isgomock struct{}
}

// MockbranchRepositoryMockRecorder is the mock recorder for MockbranchRepository.
type MockbranchRepositoryMockRecorder struct {
	mock *MockbranchRepository
}

// NewMockbranchRepository creates a new mock instance.
func NewMockbranchRepository(ctrl *gomock.Controller) *MockbranchRepository {
	mock := &MockbranchRepository{ctrl: ctrl}
	mock.recorder = &MockbranchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbranchRepository) EXPECT() *MockbranchRepositoryMockRecorder {
	return m.recorder
}

// GetByProjectIDAndID mocks base method.
func (m *MockbranchRepository) GetByProjectIDAndID(ctx context.Context, projectID, branchID snow.ID) (*domain.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectIDAndID", ctx, projectID, branchID)
	ret0, _ := ret[0].(*domain.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectIDAndID indicates an expected call of GetByProjectIDAndID.
func (mr *MockbranchRepositoryMockRecorder) GetByProjectIDAndID(ctx, projectID, branchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectIDAndID", reflect.TypeOf((*MockbranchRepository)(nil).GetByProjectIDAndID), ctx, projectID, branchID)
}

// GetDefaultBranch mocks base method.
func (m *MockbranchRepository) GetDefaultBranch(ctx context.Context, projectID snow.ID) (*domain.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultBranch", ctx, projectID)
	ret0, _ := ret[0].(*domain.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultBranch indicates an expected call of GetDefaultBranch.
func (mr *MockbranchRepositoryMockRecorder) GetDefaultBranch(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultBranch", reflect.TypeOf((*MockbranchRepository)(nil).GetDefaultBranch), ctx, projectID)
}

// ListBranches mocks base method.
func (m *MockbranchRepository) ListBranches(ctx context.Context, projectID snow.ID, limit int, updatedAfter *time.Time, lastID snow.ID) ([]*domain.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBranches", ctx, projectID, limit, updatedAfter, lastID)
	ret0, _ := ret[0].([]*domain.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBranches indicates an expected call of ListBranches.
func (mr *MockbranchRepositoryMockRecorder) ListBranches(ctx, projectID, limit, updatedAfter, lastID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBranches", reflect.TypeOf((*MockbranchRepository)(nil).ListBranches), ctx, projectID, limit, updatedAfter, lastID)
}
